### ISSUE TITLE
Bidirectional Multi-layer RNN with LSTM with Own Dataset in CSV Format (AG News)

### ISSUE THREAD

**Issue by taufique74** [rasbt/deeplearning-models#35]
In this notebook, while defining the model you didn't apply `self.fc2()`
So the shape of the returned tensor is `(128, 64)` instead of `(128, 4)`.
But the interesting part is that it still achieves great accuracy. Now I'm just wondering why it is working.
Also, `model(text, text_lengths)` returns a tensor of size `(128, 64)`, so why are we calling `.squeeze(1)` on that tensor? 
Since the second dimension is not 1, the tensor shape remains the same. Is there any edge case we are dealing with?

**Comment by rasbt** [comment]
Good catch. Not sure what was going on there! It's been some time ago, and I am not sure why I used squeeze here. Not necessary like you said. I updated this.

Btw using the second fc layer slightly decreased performance. My guess is because of overfitting. In any case. I updated the Nb. Many thanks.
